---
title: "Proposal"
date: "11/6/2018"
output: github_document
---

# Group members

# Project title

Factors Associated with Mental Health

# Motivation

1. Wh

In this project, we want to apply what we learn in "Data Science I" to a dataset we interested in and get some useful and interesting results. As a results, we can not only practice our skills of collecting data as well as analyzing data but also create something meaningful.

# Intended final products

After few weeks work, we hope that we can get a will-built website which shows our anlysis of the dataset and conclusions. This website will including our data source and some pictures created from data which reflect results. We will also make a short video which explain how we get our data, how we anlyze it and what results we get.

# Anticipated data source

The original dataset is from [Open Sourcing Mental Illness](https://osmihelp.org/research/)

# Planned challenges

1. Date is getting from survey and is untidy

The dataset we obtain is untidy. Screening through rows, some observation values are absolutely mistakes (like age = -1726). And regarding the gender identity, people use different definition of gender type (like some people think they are "something kinda of female").  

2. Incredible plot

We intend to draw a map which shows the geolocation of participants surveyed. 

# Planned timeline

Time          | Task
------------- | -----------------------------------------------
Nov 16 - 20   | Decide data set and aims of analysis
Nov 21 - 25   | Decide problems we interested in
Nov 26 - 30   | Analyze data and visualize
Dec 1 - 6     | Report, webpage, screencast and Peer assessment
Dec 7 - 11    | Prepare discussion
